//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recharge
    {
        public int RechargeID { get; set; }
        public int UserID { get; set; }
        public decimal RechargeAmount { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal CurrentBalance { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string RechargeUserName { get; set; }
        public bool IsDel { get; set; }
    
        public virtual User User { get; set; }
    }
}
