
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace PP.WaiMai.Model
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.Order = new HashSet<Order>();

        this.Recharge = new HashSet<Recharge>();

        this.Comment = new HashSet<Comment>();

        this.ExpendLog = new HashSet<ExpendLog>();

        this.Sarcasm = new HashSet<Sarcasm>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string IPAddress { get; set; }

    public decimal Amount { get; set; }

    public bool IsAdmin { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool IsDel { get; set; }

    public int DepartmentType { get; set; }



    public virtual ICollection<Order> Order { get; set; }

    public virtual ICollection<Recharge> Recharge { get; set; }

    public virtual ICollection<Comment> Comment { get; set; }

    public virtual ICollection<ExpendLog> ExpendLog { get; set; }

    public virtual ICollection<Sarcasm> Sarcasm { get; set; }

}

}
