//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PP.WaiMai.Model
{
	public partial class Account
	{
		public Account ToPOCO(bool isPOCO = true){
			return new Account(){
				AccountID = this.AccountID,
				AccountName = this.AccountName,
				IPAddress = this.IPAddress,
				Amount = this.Amount,
				CreateDate = this.CreateDate,
				IsDel = this.IsDel,
			};
		}
	}
}
