//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PP.WaiMai.Model
{
	public partial class ExpendLog
	{
		public ExpendLog ToPOCO(bool isPOCO = true){
			return new ExpendLog(){
				ExpendLogID = this.ExpendLogID,
				CreateDate = this.CreateDate,
				ConsumeAmount = this.ConsumeAmount,
				RechargeAmount = this.RechargeAmount,
				Description = this.Description,
				ExpendLogType = this.ExpendLogType,
				ExpendLogTypeID = this.ExpendLogTypeID,
				UserID = this.UserID,
			};
		}
	}
}
