
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

namespace PP.WaiMai.Model
{
	public partial class Restaurant
	{

		public Restaurant ToPOCO(bool isPOCO = true){
			return new Restaurant(){

				RestaurantID = this.RestaurantID,

				RestaurantName = this.RestaurantName,

				SendOutCount = this.SendOutCount,

				TakeoutPhone = this.TakeoutPhone,

				Description = this.Description,

				IsEnable = this.IsEnable,

				CreateDate = this.CreateDate,

				Creator = this.Creator,

				EditDate = this.EditDate,

				Editor = this.Editor,

				IsDel = this.IsDel,

				Version = this.Version,

			};
		}
	}

}
