
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

namespace PP.WaiMai.Model
{
	public partial class User
	{

		public User ToPOCO(bool isPOCO = true){
			return new User(){

				UserID = this.UserID,

				UserName = this.UserName,

				Password = this.Password,

				IPAddress = this.IPAddress,

				Amount = this.Amount,

				IsAdmin = this.IsAdmin,

				CreateDate = this.CreateDate,

				IsDel = this.IsDel,

				DepartmentType = this.DepartmentType,

			};
		}
	}

}
